DROP SEQUENCE "TRIAGEM_SEQ";
DROP SEQUENCE "MEDICAMENTOS_SEQ";
DROP TABLE "DOENTE" CASCADE CONSTRAINTS;
DROP TABLE "TRIAGEM" CASCADE CONSTRAINTS;
DROP TABLE "MEDICAMENTOSSTOCK" CASCADE CONSTRAINTS;
DROP TABLE "MEDICAMENTOSPEDIDOS" CASCADE CONSTRAINTS;
DROP TABLE "RECEITA" CASCADE CONSTRAINTS;
DROP TABLE "REGISTOENTRADA" CASCADE CONSTRAINTS;
DROP TABLE "REGISTOSAIDA" CASCADE CONSTRAINTS;
DROP TABLE "GABINETES";
DROP TABLE "SUPPLIERS";
DROP TABLE "HOSPITALINFO";
DROP TABLE "MEDICINESINFORMATION";


 CREATE SEQUENCE   "MEDICAMENTOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
 
 CREATE SEQUENCE   "TRIAGEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

	
CREATE TABLE  "DOENTE" 
   (	"ID" NUMBER(6,0), 
	"NOME" VARCHAR2(255), 
	"DATANASC" DATE, 
	"SEGURO" VARCHAR2(255), 
	"RUA" VARCHAR2(255), 
	"NUMERO" NUMBER(6,0), 
	"ANDAR" NUMBER(6,0), 
	"APARTAMENTO" VARCHAR2(255), 
	"CODIGOPOSTAL" VARCHAR2(255) NOT NULL ENABLE, 
	"MORADAVALIDA" NUMBER(1,0),
	"FREGUESIA" VARCHAR2(255),
	"CONCELHO" VARCHAR2(255),
	"DISTRITO" VARCHAR2(255), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
   
CREATE TABLE  "TRIAGEM" 
   (	"TRIAGEMID" NUMBER(6,0) NOT NULL ENABLE, 
	"DOENTEID" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(255), 
	"NIVEL" VARCHAR2(255), 
	"CLASSIFICACAO" VARCHAR2(255), 
	"DATAHORA" DATE, 
	 CONSTRAINT "TRIAGEM_PK" PRIMARY KEY ("TRIAGEMID") ENABLE
   ); 
 	
ALTER TABLE  "TRIAGEM" ADD CONSTRAINT "TRIAGEM_FK" FOREIGN KEY ("DOENTEID") REFERENCES  "DOENTE" ("ID") ON DELETE CASCADE ENABLE;


CREATE OR REPLACE TRIGGER  "TRIAGEM_T1" 
BEFORE
insert or update on "TRIAGEM"
for each row
begin
if :NEW."TRIAGEMID" is null then
    select "TRIAGEM_SEQ".nextval into :NEW."TRIAGEMID" from dual;
  end if;
end;
/
ALTER TRIGGER  "TRIAGEM_T1" ENABLE;


CREATE TABLE  "MEDICAMENTOSSTOCK" 
   (	"MEDICAMENTOID" NUMBER(6,0) NOT NULL ENABLE, 
   	"NOME" VARCHAR2(255) NOT NULL ENABLE, 
	"SUBSTANCIA" VARCHAR2(255), 
	"DOSE" VARCHAR2(255), 
	"QUANTIDADEEXISTENTE" NUMBER(6,0) NOT NULL ENABLE, 
	"QUANTIDADECRITICA" NUMBER(6,0) NOT NULL ENABLE, 
	 CONSTRAINT "MEDICAMENTOSSTOCK_PK" PRIMARY KEY ("MEDICAMENTOID") ENABLE, 
	 CONSTRAINT "MEDICAMENTOSSTOCK_CON" UNIQUE ("NOME", "SUBSTANCIA", "DOSE") ENABLE
   ) ;


CREATE OR REPLACE TRIGGER  "MEDICAMENTOSSTOCK_T1" 
BEFORE
insert on "MEDICAMENTOSSTOCK"
for each row
begin
begin
  if :NEW."MEDICAMENTOID" is null then
    select "MEDICAMENTOS_SEQ".nextval into :NEW."MEDICAMENTOID" from dual;
  end if;
end;
end;
/
ALTER TRIGGER  "MEDICAMENTOSSTOCK_T1" ENABLE;


CREATE TABLE  "MEDICAMENTOSPEDIDOS" 
   (	"MEDICAMENTOID" NUMBER(6,0) NOT NULL ENABLE, 
	"QUANTIDADEPEDIDA" NUMBER(6,0) NOT NULL ENABLE, 
	 CONSTRAINT "MEDICAMENTOSPEDIDOS_CON" PRIMARY KEY ("MEDICAMENTOID") ENABLE
   ) ;
   
   ALTER TABLE  "MEDICAMENTOSPEDIDOS" ADD CONSTRAINT "MEDICAMENTOSPEDIDOS_FK" FOREIGN KEY ("MEDICAMENTOID")
	  REFERENCES  "MEDICAMENTOSSTOCK" ("MEDICAMENTOID") ON DELETE CASCADE ENABLE;

CREATE TABLE  "RECEITA" 
   (	"MEDICAMENTOID" NUMBER(6,0) NOT NULL ENABLE, 
	"TRIAGEM" NUMBER(6,0) NOT NULL ENABLE, 
	"DOENTEID" NUMBER(6,0), 
	"DESCONTINUADA" VARCHAR2(3),
	 CONSTRAINT "RECEITA_PK" PRIMARY KEY ("MEDICAMENTOID", "TRIAGEM") ENABLE
   ) ;
   
   ALTER TABLE  "RECEITA" ADD CONSTRAINT "RECEITA_FK" FOREIGN KEY ("TRIAGEM")
	  REFERENCES  "TRIAGEM" ("TRIAGEMID") ON DELETE CASCADE ENABLE;
	  
   ALTER TABLE  "RECEITA" ADD CONSTRAINT "RECEITA_FK2" FOREIGN KEY ("MEDICAMENTOID")
	  REFERENCES  "MEDICAMENTOSSTOCK" ("MEDICAMENTOID") ON DELETE CASCADE ENABLE;


CREATE OR REPLACE TRIGGER  "RECEITA_T1" 
BEFORE
insert on "RECEITA"
for each row
begin
if :NEW.TRIAGEM is null then
    select max("TRIAGEM".TRIAGEMID) into :NEW.TRIAGEM from "TRIAGEM" where "TRIAGEM".DOENTEID = :NEW.DOENTEID;
  end if;
end;

/
ALTER TRIGGER  "RECEITA_T1" ENABLE;


CREATE TABLE  "REGISTOENTRADA" 
   (	"DATAHORA" DATE, 
	"DOENTEID" NUMBER(6,0), 
	 CONSTRAINT "REGISTOENTRADA_PK" PRIMARY KEY ("DATAHORA", "DOENTEID") ENABLE
   ) ;
   
   ALTER TABLE  "REGISTOENTRADA" ADD CONSTRAINT "REGISTOENTRADA_FK" FOREIGN KEY ("DOENTEID")
	  REFERENCES  "DOENTE" ("ID") ON DELETE CASCADE ENABLE;

CREATE TABLE  "REGISTOSAIDA" 
   (	"DATAHORA" DATE, 
	"DOENTEID" NUMBER(6,0), 
	"SATISFACAORECEITAELECTRONICA" VARCHAR2(255), 
	"CLASSIFICACAOATENDIMENTO" VARCHAR2(255), 
	"SATISFACAOTEMPOESPERA" VARCHAR2(255), 
	"COMENTARIOS" VARCHAR2(255), 
	 CONSTRAINT "REGISTOSAIDA_PK" PRIMARY KEY ("DATAHORA", "DOENTEID") ENABLE
   ) ;
   
   ALTER TABLE  "REGISTOSAIDA" ADD CONSTRAINT "REGISTOSAIDA_FK" FOREIGN KEY ("DOENTEID")
	  REFERENCES  "DOENTE" ("ID") ON DELETE CASCADE ENABLE;


			
CREATE TABLE  "GABINETES" 
   (	"TIPOATENDIMENTO" VARCHAR2(255), 
	"CAPACIDADE" NUMBER(2,0), 
	"OCUPACAO" NUMBER(2,0), 
	 CONSTRAINT "GABINETES_PK" PRIMARY KEY ("TIPOATENDIMENTO") ENABLE
   ) ;

INSERT INTO "GABINETES"(TIPOATENDIMENTO, CAPACIDADE, OCUPACAO) VALUES ('Triagem', 2, 0);
INSERT INTO "GABINETES"(TIPOATENDIMENTO, CAPACIDADE, OCUPACAO) VALUES ('Ortopedia', 2, 0);
INSERT INTO "GABINETES"(TIPOATENDIMENTO, CAPACIDADE, OCUPACAO) VALUES ('Pediatria', 2, 0);
INSERT INTO "GABINETES"(TIPOATENDIMENTO, CAPACIDADE, OCUPACAO) VALUES ('Medicina Geral', 3, 0);
INSERT INTO "GABINETES"(TIPOATENDIMENTO, CAPACIDADE, OCUPACAO) VALUES ('Cirurgia', 1, 0);


CREATE TABLE  "SUPPLIERS" 
   (	"PARTYNAME" VARCHAR2(255), 
	"STREETNAME" VARCHAR2(255), 
	"CITYNAME" VARCHAR2(255), 
	"POSTALZONE" VARCHAR2(255), 
	"COUNTRY" VARCHAR2(255), 
	"CONTACTNAME" VARCHAR2(255), 
	"CONTACTTELEPHONE" VARCHAR2(255), 
	"CONTACTEMAIL" VARCHAR2(255), 
	"CUSTOMERACCOUNTID" VARCHAR2(255), 
	"PRICECHARGE" NUMBER(10,0)
   ) ;

INSERT INTO "SUPPLIERS"(PARTYNAME, STREETNAME, CITYNAME, POSTALZONE, COUNTRY, CONTACTNAME, CONTACTTELEPHONE, CONTACTEMAIL, CUSTOMERACCOUNTID, PRICECHARGE) VALUES ('Bayer Portugal, S.A', 'Rua Quinta do Pinheiro', 'Carnaxide', '2790-180', 'Portugal', 'Bayer', '214172121','bayerportugal@gmail.com', '123456', 5); 

CREATE TABLE  "HOSPITALINFO" 
   (	"CUSTOMERACCOUNTID" NUMBER(10,0), 
	"PARTYNAME" VARCHAR2(255), 
	"STREETNAME" VARCHAR2(255), 
	"CITYNAME" VARCHAR2(255), 
	"POSTALZONE" VARCHAR2(255), 
	"COUNTRY" VARCHAR2(255), 
	"CONTACTNAME" VARCHAR2(255), 
	"CONTACTTELEPHONE" VARCHAR2(255), 
	"CONTACTEMAIL" VARCHAR2(255)
   ) ;
   
INSERT INTO "HOSPITALINFO"(CUSTOMERACCOUNTID, PARTYNAME, STREETNAME, CITYNAME, POSTALZONE, COUNTRY, CONTACTNAME, CONTACTTELEPHONE, CONTACTEMAIL) VALUES (9876543, 'Hospital Sao Nuno', 'Rua da Azoia', 'Lisboa', '1450-012', 'Portugal', 'HSaoNuno', '214472125', 'hsn@gmail.com'); 

CREATE TABLE  "MEDICINESINFORMATION" 
   (	"MEDICAMENTOID" NUMBER(6,0), 
	"FORMAFARMACEUTICA" VARCHAR2(255), 
	"GENERICO" VARCHAR2(255), 
	"TITULAR" VARCHAR2(255), 
	"DATAAUTORIZACAO" VARCHAR2(255), 
	"ESTADOAUTORIZACAO" VARCHAR2(255), 
	"CLASSIFICACAODISPENSA" VARCHAR2(255), 
	"CLASSIFICACAOESTUPEFACIENTE" VARCHAR2(255), 
	"ANATOMICALCLASSIFICATION" VARCHAR2(255), 
	"CLASSIFICACAOFARMACOTERAPEUTIC" VARCHAR2(255), 
	"VIAADMINISTRACAO" VARCHAR2(255), 
	"GRUPOPRODUTO" VARCHAR2(255), 
	"NUMEROPROCESSO" VARCHAR2(255), 
	"MARGEMTERAPEUTICA" VARCHAR2(255), 
	 CONSTRAINT "MEDICINESINFORMATION_PK" PRIMARY KEY ("MEDICAMENTOID") ENABLE
   ) ;
   
   ALTER TABLE  "MEDICINESINFORMATION" ADD CONSTRAINT "MEDICINESINFORMATION_FK" FOREIGN KEY ("MEDICAMENTOID")
	  REFERENCES  "MEDICAMENTOSSTOCK" ("MEDICAMENTOID") ON DELETE CASCADE ENABLE;


		
