<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ReexecuteTriageBPELProcess.wsdl"/>
      <rootElement name="process" namespace="http://xmlns.oracle.com/SeiLessons/HSN_Project/ReexecuteTriageBPELProcess"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PatientTriageDBAdapter.wsdl"/>
      <rootElement name="TriagemCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PatientTriageDBAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU APR 25 23:16:10 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PatientTriageDBAdapter"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ReexecuteTriageBPELProcess"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/PatientTriageDBAdapter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk xsd wsdl client ns1 top bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <top:TriagemCollection>
      <top:Triagem>
        <top:triagemid>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </top:triagemid>
        <top:doenteid>
          <xsl:value-of select="/client:process/client:doenteID"/>
        </top:doenteid>
        <top:tipo>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </top:tipo>
        <top:nivel>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </top:nivel>
        <top:classificacao>
          <xsl:value-of select='"SUFICIENTE"'/>
        </top:classificacao>
        <top:datahora>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </top:datahora>
      </top:Triagem>
    </top:TriagemCollection>
  </xsl:template>
</xsl:stylesheet>
