<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExitPatientBPELProcess.wsdl"/>
      <rootElement name="receita" namespace="http://acssdatamodel.pt"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [MON MAY 06 13:44:11 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicineInformationDBAdapter"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://acssdatamodel.pt"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns2="http://saude365.pt"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl tns top xsd ns1 client ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:receita>
      <ns1:CabecalhoReceita>
        <ns1:Id>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns1:Id>
        <ns1:NumeroReceita>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns1:NumeroReceita>
      </ns1:CabecalhoReceita>
      <ns1:ListaLinhasReceita>
        <ns1:LinhaReceita>
          <ns1:Id>
            <xsl:value-of select="oraext:generate-guid()"/>
          </ns1:Id>
          <ns1:NumeroLinha>
            <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:numeroprocesso"/>
          </ns1:NumeroLinha>
          <ns1:Medicamento>
            <ns1:Codigo>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicamentoid"/>
            </ns1:Codigo>
            <ns1:Descricao>
              <xsl:value-of select='concat(/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome," ",/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose)'/>
            </ns1:Descricao>
            <ns1:TitularAIM>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:titular"/>
            </ns1:TitularAIM>
            <ns1:SubstanciaActiva>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia"/>
            </ns1:SubstanciaActiva>
            <ns1:FormaFarmaceutica>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:formafarmaceutica"/>
            </ns1:FormaFarmaceutica>
            <ns1:Embalagem>
              <xsl:value-of select='concat("Embalagem de ",/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome," ",/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose,". Via Administracao: ",/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:viaadministracao)'/>
            </ns1:Embalagem>
            <ns1:Dosagem>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose"/>
            </ns1:Dosagem>
          </ns1:Medicamento>
          <ns1:SubstituivelGenerico>
            <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:generico"/>
          </ns1:SubstituivelGenerico>
          <ns1:Quantidade>
            <xsl:value-of select="1"/>
          </ns1:Quantidade>
          <ns1:EstadoItem>
            <ns1:Descricao>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:estadoautorizacao"/>
            </ns1:Descricao>
            <ns1:DataInicio>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:dataautorizacao"/>
            </ns1:DataInicio>
          </ns1:EstadoItem>
          <ns1:DescricaoDispensa>
            <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:classificacaodispensa"/>
          </ns1:DescricaoDispensa>
        </ns1:LinhaReceita>
      </ns1:ListaLinhasReceita>
    </ns1:receita>
  </xsl:template>
</xsl:stylesheet>
