<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../GetMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SUN MAY 12 13:56:43 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicineInformationDBAdapter"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns top plt xsd wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <top:MedicamentosstockCollection>
      <top:Medicamentosstock>
        <top:medicamentoid>
          <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicamentoid"/>
        </top:medicamentoid>
        <top:nome>
          <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome"/>
        </top:nome>
        <top:substancia>
          <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia"/>
        </top:substancia>
        <top:dose>
          <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose"/>
        </top:dose>
        <top:medicinesinformationCollection>
          <top:Medicinesinformation>
            <top:formafarmaceutica>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:formafarmaceutica"/>
            </top:formafarmaceutica>
            <top:generico>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:generico"/>
            </top:generico>
            <top:titular>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:titular"/>
            </top:titular>
            <top:dataautorizacao>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:dataautorizacao"/>
            </top:dataautorizacao>
            <top:estadoautorizacao>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:estadoautorizacao"/>
            </top:estadoautorizacao>
            <top:classificacaodispensa>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:classificacaodispensa"/>
            </top:classificacaodispensa>
            <top:classificacaoestupefaciente>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:classificacaoestupefaciente"/>
            </top:classificacaoestupefaciente>
            <top:anatomicalclassification>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:anatomicalclassification"/>
            </top:anatomicalclassification>
            <top:classificacaofarmacoterapeutic>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:classificacaofarmacoterapeutic"/>
            </top:classificacaofarmacoterapeutic>
            <top:viaadministracao>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:viaadministracao"/>
            </top:viaadministracao>
            <top:grupoproduto>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:grupoproduto"/>
            </top:grupoproduto>
            <top:numeroprocesso>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:numeroprocesso"/>
            </top:numeroprocesso>
            <top:margemterapeutica>
              <xsl:value-of select="/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicinesinformationCollection/top:Medicinesinformation/top:margemterapeutica"/>
            </top:margemterapeutica>
          </top:Medicinesinformation>
        </top:medicinesinformationCollection>
      </top:Medicamentosstock>
    </top:MedicamentosstockCollection>
  </xsl:template>
</xsl:stylesheet>
