<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetAllPatientInformationDBAdapter.wsdl"/>
      <rootElement name="DoenteCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllPatientInformationDBAdapter"/>
    </source>
    <source type="WSDL">
      <schema location="../ExitPatientBPELProcess.wsdl"/>
      <rootElement name="receita" namespace="http://acssdatamodel.pt"/>
      <param name="prescriptionVariable" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExitPatientBPELProcess.wsdl"/>
      <rootElement name="receita" namespace="http://acssdatamodel.pt"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [MON MAY 06 13:49:56 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllPatientInformationDBAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://acssdatamodel.pt"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetAllPatientInformationDBAdapter"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns2="http://saude365.pt"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top plt wsdl ns1 client tns xsd ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="prescriptionVariable"/>
  <xsl:template match="/">
    <ns1:receita>
      <ns1:CabecalhoReceita>
        <ns1:Id>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns1:Id>
        <ns1:NumeroReceita>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns1:NumeroReceita>
        <ns1:Data>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </ns1:Data>
        <ns1:Utente>
          <ns1:Id>
            <xsl:value-of select="/top:DoenteCollection/top:Doente/top:id"/>
          </ns1:Id>
          <ns1:Identificao>
            <ns1:NomeCompleto>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:nome"/>
            </ns1:NomeCompleto>
            <ns1:DataNascimento>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:datanasc"/>
            </ns1:DataNascimento>
          </ns1:Identificao>
          <ns1:Morada>
            <ns1:Rua>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:rua"/>
            </ns1:Rua>
            <ns1:Porta>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:numero"/>
            </ns1:Porta>
            <ns1:Andar>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:andar"/>
            </ns1:Andar>
            <ns1:Lugar>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:apartamento"/>
            </ns1:Lugar>
            <ns1:Localidade>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:freguesia"/>
            </ns1:Localidade>
            <ns1:DistritoResidencia>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:distrito"/>
            </ns1:DistritoResidencia>
            <ns1:ConcelhoResidencia>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:concelho"/>
            </ns1:ConcelhoResidencia>
            <ns1:FreguesiaResidencia>
              <ns1:Descricao>
                <xsl:value-of select="/top:DoenteCollection/top:Doente/top:freguesia"/>
              </ns1:Descricao>
            </ns1:FreguesiaResidencia>
            <ns1:CodigoPostal>
              <xsl:value-of select="/top:DoenteCollection/top:Doente/top:codigopostal"/>
            </ns1:CodigoPostal>
          </ns1:Morada>
        </ns1:Utente>
      </ns1:CabecalhoReceita>
      <ns1:ListaLinhasReceita>
        <xsl:copy-of select="$prescriptionVariable/ns1:receita/ns1:ListaLinhasReceita/ns1:LinhaReceita"/>
      </ns1:ListaLinhasReceita>
    </ns1:receita>
  </xsl:template>
</xsl:stylesheet>
