<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../FarmaciasPortuguesasService.wsdl"/>
      <rootElement name="getFarmaciasProximasResponse" namespace="http://saude365.pt/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExitPatientFileAdapter.wsdl"/>
      <rootElement name="exitPatientReport" namespace="http://saude365.pt/exitpatient"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE MAY 07 08:01:43 PDT 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://saude365.pt/types"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:tns="http://saude365.pt/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-Project/ExitPatientFileAdapter"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageInformationDBAdapter"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns3="http://acssdatamodel.pt"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:imp1="http://saude365.pt/exitpatient"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns4="http://saude365.pt/registoentrada"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllTriageAssociatedWithPatientDBAdapter"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns5="http://saude365.pt"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 soap12 tns soap mime wsdl xsd plt ns1 ns3 imp1 ns4 jca ns6 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:exitPatientReport>
      <xsl:for-each select="/tns:getFarmaciasProximasResponse/return">
        <imp1:localPharmacies>
          <imp1:concelho>
            <xsl:value-of select='substring-after(concelho,"Concelho: ")'/>
          </imp1:concelho>
          <imp1:directorTecnico>
            <xsl:value-of select='substring-after(directorTecnico,"Director Técnico: ")'/>
          </imp1:directorTecnico>
          <imp1:distrito>
            <xsl:value-of select='substring-after(distrito,"Distrito: ")'/>
          </imp1:distrito>
          <imp1:farmaciaName>
            <xsl:value-of select="farmaciaName"/>
          </imp1:farmaciaName>
          <imp1:freguesia>
            <xsl:value-of select='substring-after(freguesia,"Freguesia: ")'/>
          </imp1:freguesia>
          <imp1:morada>
            <xsl:value-of select='substring-after(morada,"Morada: ")'/>
          </imp1:morada>
          <imp1:telefone>
            <xsl:value-of select='substring-after(telefone,"Telefone: ")'/>
          </imp1:telefone>
        </imp1:localPharmacies>
      </xsl:for-each>
    </imp1:exitPatientReport>
  </xsl:template>
</xsl:stylesheet>
