<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetTriageIDDBAdapter.wsdl"/>
      <rootElement name="GetTriageIDDBAdapterOutput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageIDDBAdapter"/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/soa/shared/workflow/TaskServiceInterface.wsdl"/>
      <rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
      <param name="ClassifyTriageHumantask1_globalVariable.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../UpdateTriageClassificationDBAdapter.wsdl"/>
      <rootElement name="TriagemCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTriageClassificationDBAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [FRI APR 26 01:50:23 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetTriageIDDBAdapter"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
                xmlns:tsc="http://xmlns.oracle.com/bpel/workflow/common/tsc"
                xmlns:ns2="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTriageClassificationDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/UpdateTriageClassificationDBAdapter"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:routingslip="http://xmlns.oracle.com/bpel/workflow/routingSlip"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns3="http://xmlns.oracle.com/bpel/workflow/taskService/schema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/taskService"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageIDDBAdapter"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl bpws tns ns1 java tsc ns2 format plt soap wsdl routingslip ns3 xsd ns0 db task top ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="ClassifyTriageHumantask1_globalVariable.payload"/>
  <xsl:template match="/">
    <top:TriagemCollection>
      <top:Triagem>
        <top:triagemid>
          <xsl:value-of select="/db:GetTriageIDDBAdapterOutput/db:MAX_TRIAGEMID_"/>
        </top:triagemid>
        <top:classificacao>
          <xsl:value-of select="$ClassifyTriageHumantask1_globalVariable.payload/task:task/task:systemAttributes/task:outcome"/>
        </top:classificacao>
      </top:Triagem>
    </top:TriagemCollection>
  </xsl:template>
</xsl:stylesheet>
