<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../InfarmedServiceService.wsdl"/>
      <rootElement name="getMedsInfoResponse" namespace="http://saude365.pt/"/>
    </source>
    <source type="WSDL">
      <schema location="../MedicineStockMedicineIDDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockMedicineIDDBAdapter"/>
      <param name="medicineStockMedicineIDDBOutputVariable.MedicamentosstockCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../InsertMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicinesinformationCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertMedicineInformationDBAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SAT MAY 04 11:32:18 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://saude365.pt/types"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertMedicineInformationDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockMedicineIDDBAdapter"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/MedicineStockMedicineIDDBAdapter"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:tns="http://saude365.pt/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/InsertMedicineInformationDBAdapter"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 top ns1 soap12 tns plt soap wsdl mime xsd ns3 ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="medicineStockMedicineIDDBOutputVariable.MedicamentosstockCollection"/>
  <xsl:template match="/">
    <ns3:MedicinesinformationCollection>
      <ns3:Medicinesinformation>
        <ns3:medicamentoid>
          <xsl:value-of select="$medicineStockMedicineIDDBOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicamentoid"/>
        </ns3:medicamentoid>
        <ns3:formafarmaceutica>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/formaFarmaceutica"/>
        </ns3:formafarmaceutica>
        <ns3:generico>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/generico"/>
        </ns3:generico>
        <ns3:titular>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/titular"/>
        </ns3:titular>
        <ns3:dataautorizacao>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/dataAutorizacao"/>
        </ns3:dataautorizacao>
        <ns3:estadoautorizacao>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/estadoAutorizacao"/>
        </ns3:estadoautorizacao>
        <ns3:classificacaodispensa>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/classificacaoDispensa"/>
        </ns3:classificacaodispensa>
        <ns3:classificacaoestupefaciente>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/classificacaoEstupefaciente"/>
        </ns3:classificacaoestupefaciente>
        <ns3:anatomicalclassification>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/anatomicalClassification"/>
        </ns3:anatomicalclassification>
        <ns3:classificacaofarmacoterapeutic>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/classificacaoFarmacoterapeutica"/>
        </ns3:classificacaofarmacoterapeutic>
        <ns3:viaadministracao>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/viaAdministracao"/>
        </ns3:viaadministracao>
        <ns3:grupoproduto>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/grupoProduto"/>
        </ns3:grupoproduto>
        <ns3:numeroprocesso>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/numeroProcesso"/>
        </ns3:numeroprocesso>
        <ns3:margemterapeutica>
          <xsl:value-of select="/tns:getMedsInfoResponse/return/margemTerapeutica"/>
        </ns3:margemterapeutica>
      </ns3:Medicinesinformation>
    </ns3:MedicinesinformationCollection>
  </xsl:template>
</xsl:stylesheet>
