<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ExitPatientFileAdapter.wsdl"/>
      <rootElement name="exitPatientReport" namespace="http://saude365.pt/exitpatient"/>
    </source>
    <source type="WSDL">
      <schema location="../ExitPatientFileAdapter.wsdl"/>
      <rootElement name="exitPatientReport" namespace="http://saude365.pt/exitpatient"/>
      <param name="exitPatientElectronicalPrescriptionVariable.body" />
    </source>
    <source type="WSDL">
      <schema location="../ExitPatientFileAdapter.wsdl"/>
      <rootElement name="exitPatientReport" namespace="http://saude365.pt/exitpatient"/>
      <param name="triagesExitPatientVariable.body" />
    </source>
    <source type="WSDL">
      <schema location="../GetEntryRegisterDBAdapter.wsdl"/>
      <rootElement name="GetEntryRegisterDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetEntryRegisterDBAdapter"/>
      <param name="getEntryRegisterOutputVariable.GetEntryRegisterDBAdapterOutputCollection" />
    </source>
    <source type="WSDL">
      <schema location="../GetAllPatientInformationDBAdapter.wsdl"/>
      <rootElement name="DoenteCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllPatientInformationDBAdapter"/>
      <param name="getAllPatientInformationOutputVariable.DoenteCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ExitPatientFileAdapter.wsdl"/>
      <rootElement name="exitPatientReport" namespace="http://saude365.pt/exitpatient"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE MAY 07 06:55:35 PDT 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetEntryRegisterDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllPatientInformationDBAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-Project/ExitPatientFileAdapter"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetEntryRegisterDBAdapter"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://acssdatamodel.pt"
                xmlns:imp1="http://saude365.pt/exitpatient"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetAllPatientInformationDBAdapter"
                xmlns:ns2="http://saude365.pt/registoentrada"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetAllTriageAssociatedWithPatientDBAdapter"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns3 top plt wsdl tns db ns1 imp1 ns4 ns2 jca ns0 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="exitPatientElectronicalPrescriptionVariable.body"/>
  <xsl:param name="triagesExitPatientVariable.body"/>
  <xsl:param name="getEntryRegisterOutputVariable.GetEntryRegisterDBAdapterOutputCollection"/>
  <xsl:param name="getAllPatientInformationOutputVariable.DoenteCollection"/>
  <xsl:template match="/">
    <imp1:exitPatientReport>
      <imp1:dateTime>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </imp1:dateTime>
      <imp1:entryReport>
        <ns2:dataHora>
          <xsl:value-of select="$getEntryRegisterOutputVariable.GetEntryRegisterDBAdapterOutputCollection/db:GetEntryRegisterDBAdapterOutputCollection/db:GetEntryRegisterDBAdapterOutput/db:DATAHORA"/>
        </ns2:dataHora>
        <ns2:doente>
          <ns2:nome>
            <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:nome"/>
          </ns2:nome>
          <ns2:dataNasc>
            <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:datanasc"/>
          </ns2:dataNasc>
          <ns2:id>
            <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:id"/>
          </ns2:id>
          <ns2:seguroSaude>
            <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:seguro"/>
          </ns2:seguroSaude>
          <ns2:morada>
            <ns2:codigoPostal>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:codigopostal"/>
            </ns2:codigoPostal>
            <ns2:rua>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:rua"/>
            </ns2:rua>
            <ns2:num>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:numero"/>
            </ns2:num>
            <ns2:andar>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:andar"/>
            </ns2:andar>
            <ns2:apartamento>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:apartamento"/>
            </ns2:apartamento>
            <ns2:concelho>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:concelho"/>
            </ns2:concelho>
            <ns2:distrito>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:distrito"/>
            </ns2:distrito>
            <ns2:freguesia>
              <xsl:value-of select="$getAllPatientInformationOutputVariable.DoenteCollection/top:DoenteCollection/top:Doente/top:freguesia"/>
            </ns2:freguesia>
          </ns2:morada>
        </ns2:doente>
      </imp1:entryReport>
      <xsl:copy-of select="$triagesExitPatientVariable.body/imp1:exitPatientReport/imp1:triageReport">
        <?oracle-xsl-mapper-position imp1:triageReport?>
      </xsl:copy-of>
      <imp1:electronicalPrescription>
        <xsl:value-of select="$exitPatientElectronicalPrescriptionVariable.body/imp1:exitPatientReport/imp1:electronicalPrescription"/>
        <xsl:copy-of select="$exitPatientElectronicalPrescriptionVariable.body/imp1:exitPatientReport/imp1:electronicalPrescription/ns1:CabecalhoReceita">
          <?oracle-xsl-mapper-position ns1:CabecalhoReceita?>
        </xsl:copy-of>
        <xsl:copy-of select="$exitPatientElectronicalPrescriptionVariable.body/imp1:exitPatientReport/imp1:electronicalPrescription/ns1:ListaLinhasReceita">
          <?oracle-xsl-mapper-position ns1:ListaLinhasReceita?>
        </xsl:copy-of>
      </imp1:electronicalPrescription>
      <xsl:copy-of select="/imp1:exitPatientReport/imp1:localPharmacies">
        <?oracle-xsl-mapper-position imp1:localPharmacies?>
      </xsl:copy-of>
    </imp1:exitPatientReport>
  </xsl:template>
</xsl:stylesheet>
