<?binding.jca EntryRegisterDBAdapter_db.jca?>
<wsdl:definitions name="EntryRegisterDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/EntryRegisterDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/EntryRegisterDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EntryRegisterDBAdapter">
    <plt:partnerLinkType name="EntryRegisterDBAdapter_plt">
        <plt:role name="EntryRegisterDBAdapter_role">
            <plt:portType name="tns:EntryRegisterDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EntryRegisterDBAdapter" schemaLocation="xsd/EntryRegisterDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="RegistoentradaCollection_msg">
        <wsdl:part name="RegistoentradaCollection" element="top:RegistoentradaCollection"/>
    </wsdl:message>
    <wsdl:portType name="EntryRegisterDBAdapter_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:RegistoentradaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
