<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ExitPatientBPELProcess"
     targetNamespace="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
     xmlns:ns2="http://saude365.pt"
     xmlns:ns1="http://acssdatamodel.pt"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ExitPatientBPELProcess">
        <plnk:role name="ExitPatientBPELProcessProvider">
            <plnk:portType name="client:ExitPatientBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://acssdatamodel.pt" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
                 schemaLocation="xsd/ExitPatientBPELProcess.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://acssdatamodel.pt"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/ExitPatientBPELProcess"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <xsd:import namespace="http://acssdatamodel.pt" schemaLocation="xsd/ACSSDataModel.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://saude365.pt" schemaLocation="xsd/medicines.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ExitPatientBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="ExitPatientBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:ExitPatientBPELProcessRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
