<?binding.jca GetEntryRegisterDBAdapter_db.jca?>
<wsdl:definitions name="GetEntryRegisterDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetEntryRegisterDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetEntryRegisterDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetEntryRegisterDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetEntryRegisterDBAdapter_plt">
        <plt:role name="GetEntryRegisterDBAdapter_role">
            <plt:portType name="tns:GetEntryRegisterDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetEntryRegisterDBAdapter" schemaLocation="xsd/GetEntryRegisterDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetEntryRegisterDBAdapterInput_msg">
        <wsdl:part name="GetEntryRegisterDBAdapterInput_msg" element="db:GetEntryRegisterDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetEntryRegisterDBAdapterOutputCollection_msg">
        <wsdl:part name="GetEntryRegisterDBAdapterOutputCollection" element="db:GetEntryRegisterDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetEntryRegisterDBAdapter_ptt">
        <wsdl:operation name="GetEntryRegisterDBAdapter">
            <wsdl:input message="tns:GetEntryRegisterDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetEntryRegisterDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
