<?binding.jca GetMedicineQuantityDBAdapter_db.jca?>
<wsdl:definitions name="GetMedicineQuantityDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicineQuantityDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicineQuantityDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineQuantityDBAdapter">
    <plt:partnerLinkType name="GetMedicineQuantityDBAdapter_plt">
        <plt:role name="GetMedicineQuantityDBAdapter_role">
            <plt:portType name="tns:GetMedicineQuantityDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineQuantityDBAdapter" schemaLocation="xsd/GetMedicineQuantityDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:MedicamentospedidosPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="MedicamentospedidosCollection_msg">
        <wsdl:part name="MedicamentospedidosCollection" element="top:MedicamentospedidosCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetMedicineQuantityDBAdapter_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:MedicamentospedidosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
