<?binding.jca GetMedicinesAssociatedWithTriageDBAdapter_db.jca?>
<wsdl:definitions name="GetMedicinesAssociatedWithTriageDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicinesAssociatedWithTriageDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetMedicinesAssociatedWithTriageDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicinesAssociatedWithTriageDBAdapter">
    <plt:partnerLinkType name="GetMedicinesAssociatedWithTriageDBAdapter_plt">
        <plt:role name="GetMedicinesAssociatedWithTriageDBAdapter_role">
            <plt:portType name="tns:GetMedicinesAssociatedWithTriageDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicinesAssociatedWithTriageDBAdapter" schemaLocation="xsd/GetMedicinesAssociatedWithTriageDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetMedicinesAssociatedWithTriageDBAdapterSelect_inputParameters">
        <wsdl:part name="GetMedicinesAssociatedWithTriageDBAdapterSelect_inputParameters" element="top:GetMedicinesAssociatedWithTriageDBAdapterSelect_TRIAGEMIDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ReceitaCollection_msg">
        <wsdl:part name="ReceitaCollection" element="top:ReceitaCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetMedicinesAssociatedWithTriageDBAdapter_ptt">
        <wsdl:operation name="GetMedicinesAssociatedWithTriageDBAdapterSelect">
            <wsdl:input message="tns:GetMedicinesAssociatedWithTriageDBAdapterSelect_inputParameters"/>
            <wsdl:output message="tns:ReceitaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
