<?binding.jca GetPatientNameBirthAndInsuranceDBAdapter_db.jca?>
<wsdl:definitions name="GetPatientNameBirthAndInsuranceDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetPatientNameBirthAndInsuranceDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetPatientNameBirthAndInsuranceDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetPatientInformationDBAdapter">
    <plt:partnerLinkType name="GetPatientNameBirthAndInsuranceDBAdapter_plt">
        <plt:role name="GetPatientNameBirthAndInsuranceDBAdapter_role">
            <plt:portType name="tns:GetPatientNameBirthAndInsuranceDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetPatientInformationDBAdapter" schemaLocation="xsd/GetPatientNameBirthAndInsuranceDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:DoentePrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="DoenteCollection_msg">
        <wsdl:part name="DoenteCollection" element="top:DoenteCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetPatientNameBirthAndInsuranceDBAdapter_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:DoenteCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
