<?binding.jca GetTriageIDDBAdapter_db.jca?>
<wsdl:definitions name="GetTriageIDDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetTriageIDDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageIDDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetTriageIDDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetTriageIDDBAdapter_plt">
        <plt:role name="GetTriageIDDBAdapter_role">
            <plt:portType name="tns:GetTriageIDDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageIDDBAdapter" schemaLocation="xsd/GetTriageIDDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetTriageIDDBAdapterInput_msg">
        <wsdl:part name="GetTriageIDDBAdapterInput_msg" element="db:GetTriageIDDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetTriageIDDBAdapterOutput_msg">
        <wsdl:part name="GetTriageIDDBAdapterOutput" element="db:GetTriageIDDBAdapterOutput"/>
    </wsdl:message>
    <wsdl:portType name="GetTriageIDDBAdapter_ptt">
        <wsdl:operation name="GetTriageIDDBAdapter">
            <wsdl:input message="tns:GetTriageIDDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetTriageIDDBAdapterOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
