<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="InfarmedServiceService"
     targetNamespace="http://saude365.pt/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://saude365.pt/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ValidateMedicinesService">
        <plnk:role name="InfarmedService">
            <plnk:portType name="tns:InfarmedService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://saude365.pt/" location="InfarmedServiceService.wsdl"/>
</wsdl:definitions>
