<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MedicinesPrescriptionBPELProcess"
     targetNamespace="http://xmlns.oracle.com/SeiLessons/HSN_Project/MedicinesPrescriptionBPELProcess"
     xmlns:ns2="http://saude365.pt/prescription"
     xmlns:ns1="http://saude365.pt"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/MedicinesPrescriptionBPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="MedicinesPrescriptionBPELProcess">
        <plnk:role name="MedicinesPrescriptionBPELProcessProvider">
            <plnk:portType name="client:MedicinesPrescriptionBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://saude365.pt" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/MedicinesPrescriptionBPELProcess"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://saude365.pt/prescription">
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://saude365.pt" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_Project/MedicinesPrescriptionBPELProcess"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://saude365.pt/prescription">
            <xsd:import namespace="http://saude365.pt" schemaLocation="xsd/medicines.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="MedicinesPrescriptionBPELProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:prescriptionElement"/>
    </wsdl:message>
    <wsdl:portType name="MedicinesPrescriptionBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:MedicinesPrescriptionBPELProcessRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
