<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="MedicinesStockManagementBPELProcess"
     targetNamespace="http://xmlns.oracle.com/SeiLessons/HSN_BO/MedicinesStockManagementBPELProcess"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_BO/MedicinesStockManagementBPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="MedicinesStockManagementBPELProcess">
        <plnk:role name="MedicinesStockManagementBPELProcessProvider">
            <plnk:portType name="client:MedicinesStockManagementBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SeiLessons/HSN_BO/MedicinesStockManagementBPELProcess"
                 schemaLocation="xsd/MedicinesStockManagementBPELProcess_1.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MedicinesStockManagementBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="MedicinesStockManagementBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:MedicinesStockManagementBPELProcessRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
