<?binding.jca UpdateOfficeOcupationDBAdapter_db.jca?>
<wsdl:definitions name="UpdateOfficeOcupationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/UpdateOfficeOcupationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/UpdateOfficeOcupationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOfficeOcupationDBAdapter">
    <plt:partnerLinkType name="UpdateOfficeOcupationDBAdapter_plt">
        <plt:role name="UpdateOfficeOcupationDBAdapter_role">
            <plt:portType name="tns:UpdateOfficeOcupationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOfficeOcupationDBAdapter" schemaLocation="xsd/UpdateOfficeOcupationDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GabinetesCollection_msg">
        <wsdl:part name="GabinetesCollection" element="top:GabinetesCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateOfficeOcupationDBAdapter_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:GabinetesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
