<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetSupplierInformationDBAdapter.wsdl"/>
      <rootElement name="GetSupplierInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter"/>
    </source>
    <source type="WSDL">
      <schema location="../GetHospitalInformationDBAdapter.wsdl"/>
      <rootElement name="GetHospitalInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter"/>
      <param name="getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection" />
    </source>
    <source type="WSDL">
      <schema location="../GetMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"/>
      <param name="getMedicineInformationOutputVariable.MedicamentosstockCollection" />
    </source>
    <source type="WSDL">
      <schema location="../PlaceMedicineOrderBPELProcess.wsdl"/>
      <rootElement name="GetMedicineStockAndRequestedInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"/>
      <param name="inputVariable.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PlaceMedicineOrderBPELProcess.wsdl"/>
      <rootElement name="message" namespace="urn:netdocs:schemas:message"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SUN APR 14 19:46:46 WEST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetSupplierInformationDBAdapter"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetHospitalInformationDBAdapter"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns5="urn:netdocs:schemas:message"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetMedicineInformationDBAdapter"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_BO/PlaceMedicineOrderBPELProcess"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns3="urn:netdocs:schemas:document"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns1 db ns5 plt wsdl ns2 top client ns3 xsd ns4 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection"/>
  <xsl:param name="getMedicineInformationOutputVariable.MedicamentosstockCollection"/>
  <xsl:param name="inputVariable.payload"/>
  <xsl:template match="/">
    <xsl:variable name="ID">IST01</xsl:variable>
    <xsl:variable name="UnitOfMeasure">EA</xsl:variable>
    <xsl:variable name="currency">EUR</xsl:variable>
    <xsl:variable name="CountryCode">PT</xsl:variable>
    <ns5:message>
      <xsl:attribute name="id">
        <xsl:value-of select="oraext:generate-guid()"/>
      </xsl:attribute>
      <xsl:attribute name="creationDateTime">
        <xsl:value-of select="xp20:current-dateTime()"/>
      </xsl:attribute>
      <sender>
        <id>
          <xsl:attribute name="entityIdTypeCoded">
            <xsl:text disable-output-escaping="no">NETDOCSID</xsl:text>
          </xsl:attribute>
          <xsl:value-of select="$ID"/>
        </id>
        <name>
          <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PARTYNAME"/>
        </name>
        <addressInformation>
          <address>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:STREETNAME"/>
          </address>
          <city>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CITYNAME"/>
          </city>
          <postalCode>
            <zip>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:POSTALZONE"/>
            </zip>
            <area>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CITYNAME"/>
            </area>
          </postalCode>
          <countryCode>
            <xsl:value-of select="$CountryCode"/>
          </countryCode>
        </addressInformation>
        <contactInformation>
          <phone>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTTELEPHONE"/>
          </phone>
          <email>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTEMAIL"/>
          </email>
        </contactInformation>
      </sender>
      <receiver>
        <id>
          <xsl:attribute name="entityIdTypeCoded">
            <xsl:text disable-output-escaping="no">VAT</xsl:text>
          </xsl:attribute>
          <xsl:value-of select="501507930"/>
        </id>
        <name>
          <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:PARTYNAME"/>
        </name>
        <addressInformation>
          <address>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:STREETNAME"/>
          </address>
          <city>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
          </city>
          <postalCode>
            <zip>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:POSTALZONE"/>
            </zip>
            <area>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
            </area>
          </postalCode>
          <countryCode>
            <xsl:value-of select="$CountryCode"/>
          </countryCode>
        </addressInformation>
        <contactInformation>
          <phone>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTTELEPHONE"/>
          </phone>
          <email>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTEMAIL"/>
          </email>
        </contactInformation>
      </receiver>
      <ns3:invoice>
        <?oracle-xsl-mapper-position ns5:genericDocument?>
        <xsl:attribute name="documentNumber">
          <xsl:value-of select="oraext:generate-guid()"/>
        </xsl:attribute>
        <xsl:attribute name="documentDate">
          <xsl:value-of select="xp20:current-date()"/>
        </xsl:attribute>
        <xsl:attribute name="schemaVersion">
          <xsl:text disable-output-escaping="no">1.0</xsl:text>
        </xsl:attribute>
        <seller>
          <id>
            <xsl:attribute name="entityIdTypeCoded">
              <xsl:text disable-output-escaping="no">NETDOCSID</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="$ID"/>
          </id>
          <name>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PARTYNAME"/>
          </name>
          <addressInformation>
            <address>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:STREETNAME"/>
            </address>
            <city>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CITYNAME"/>
            </city>
            <postalCode>
              <zip>
                <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:POSTALZONE"/>
              </zip>
              <area>
                <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CITYNAME"/>
              </area>
            </postalCode>
            <countryCode>
              <xsl:value-of select="$CountryCode"/>
            </countryCode>
          </addressInformation>
          <contactInformation>
            <phone>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTTELEPHONE"/>
            </phone>
            <email>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTEMAIL"/>
            </email>
          </contactInformation>
          <vatNumber>
            <xsl:value-of select="501507930"/>
          </vatNumber>
          <commercialRegistrationNumber>
            <xsl:value-of select="number(0.0)"/>
          </commercialRegistrationNumber>
          <commercialRegistrationLocation>
            <xsl:value-of select="number(0.0)"/>
          </commercialRegistrationLocation>
          <socialCapital>
            <xsl:value-of select="50000"/>
          </socialCapital>
        </seller>
        <buyer>
          <id>
            <xsl:attribute name="entityIdTypeCoded">
              <xsl:text disable-output-escaping="no">VAT</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="501507930"/>
          </id>
          <name>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:PARTYNAME"/>
          </name>
          <addressInformation>
            <address>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:STREETNAME"/>
            </address>
            <city>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
            </city>
            <postalCode>
              <zip>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:POSTALZONE"/>
              </zip>
              <area>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
              </area>
            </postalCode>
            <countryCode>
              <xsl:value-of select="$CountryCode"/>
            </countryCode>
          </addressInformation>
          <contactInformation>
            <phone>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTTELEPHONE"/>
            </phone>
            <email>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTEMAIL"/>
            </email>
          </contactInformation>
          <vatNumber>
            <xsl:value-of select="501507930"/>
          </vatNumber>
        </buyer>
        <billTo>
          <id>
            <xsl:attribute name="entityIdTypeCoded">
              <xsl:text disable-output-escaping="no">VAT</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="501507930"/>
          </id>
          <name>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:PARTYNAME"/>
          </name>
          <addressInformation>
            <address>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:STREETNAME"/>
            </address>
            <city>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
            </city>
            <postalCode>
              <zip>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:POSTALZONE"/>
              </zip>
              <area>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
              </area>
            </postalCode>
            <countryCode>
              <xsl:value-of select="$CountryCode"/>
            </countryCode>
          </addressInformation>
          <contactInformation>
            <phone>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTTELEPHONE"/>
            </phone>
            <email>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTEMAIL"/>
            </email>
          </contactInformation>
          <vatNumber>
            <xsl:value-of select="501507930"/>
          </vatNumber>
        </billTo>
        <shipTo>
          <id>
            <xsl:attribute name="entityIdTypeCoded">
              <xsl:text disable-output-escaping="no">VAT</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="501507930"/>
          </id>
          <name>
            <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:PARTYNAME"/>
          </name>
          <addressInformation>
            <address>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:STREETNAME"/>
            </address>
            <city>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
            </city>
            <postalCode>
              <zip>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:POSTALZONE"/>
              </zip>
              <area>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CITYNAME"/>
              </area>
            </postalCode>
            <countryCode>
              <xsl:value-of select="$CountryCode"/>
            </countryCode>
          </addressInformation>
          <contactInformation>
            <phone>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTTELEPHONE"/>
            </phone>
            <email>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutputCollection/ns0:GetHospitalInformationDBAdapterOutput/ns0:CONTACTEMAIL"/>
            </email>
          </contactInformation>
        </shipTo>
        <currencyCode>
          <xsl:value-of select="$currency"/>
        </currencyCode>
        <lineItem>
          <xsl:attribute name="number">
            <xsl:text disable-output-escaping="no">1</xsl:text>
          </xsl:attribute>
          <sellerItemCode>
            <xsl:value-of select="concat($getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicamentoid,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose)"/>
          </sellerItemCode>
          <description>
            <xsl:value-of select="concat($getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose)"/>
          </description>
          <quantity>
            <value>
              <xsl:value-of select="$inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADECRITICA + $inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADEPEDIDA"/>
            </value>
            <unitOfMeasure>
              <xsl:value-of select="$UnitOfMeasure"/>
            </unitOfMeasure>
          </quantity>
          <additionalDate>
            <xsl:attribute name="type">
              <xsl:text disable-output-escaping="no">CUSTOMERAVAILABLE</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </additionalDate>
          <grossUnitPrice>
            <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE"/>
          </grossUnitPrice>
          <priceBasisQuantity>
            <value>
              <xsl:value-of select="/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE"/>
            </value>
            <unitOfMeasure>
              <xsl:value-of select="$UnitOfMeasure"/>
            </unitOfMeasure>
          </priceBasisQuantity>
          <vatPercentage>
            <xsl:value-of select="number(6.0)"/>
          </vatPercentage>
          <vatAmount>
            <xsl:value-of select="(($inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADECRITICA + $inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADEPEDIDA) * /db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE) * 0.06"/>
          </vatAmount>
          <netAmount>
            <xsl:value-of select="number(20.0)"/>
          </netAmount>
        </lineItem>
        <vatSummary>
          <vatPercentage>
            <xsl:value-of select="6"/>
          </vatPercentage>
          <vatAmount>
            <xsl:value-of select="number(20.0 * 0.06)"/>
          </vatAmount>
          <taxableAmount>
            <xsl:value-of select="number(6.0) * 20.0"/>
          </taxableAmount>
        </vatSummary>
        <totalVatAmount>
          <xsl:value-of select="(($inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADECRITICA + $inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADEPEDIDA) * /db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE) * 0.06"/>
        </totalVatAmount>
        <totalTaxableAmount>
          <xsl:value-of select="20.0 * 0.06"/>
        </totalTaxableAmount>
        <totalPayableAmount>
          <xsl:value-of select="(/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE * ($inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADECRITICA + $inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADEPEDIDA)) + ((/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE * ($inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADECRITICA + $inputVariable.payload/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns4:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns4:QUANTIDADEPEDIDA)) * 0.06)"/>
        </totalPayableAmount>
      </ns3:invoice>
    </ns5:message>
  </xsl:template>
</xsl:stylesheet>
