<?binding.jca GetHospitalInformationDBAdapter_db.jca?>
<wsdl:definitions name="GetHospitalInformationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetHospitalInformationDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetHospitalInformationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetHospitalInformationDBAdapter_plt">
        <plt:role name="GetHospitalInformationDBAdapter_role">
            <plt:portType name="tns:GetHospitalInformationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter" schemaLocation="xsd/GetHospitalInformationDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetHospitalInformationDBAdapterInput_msg">
        <wsdl:part name="GetHospitalInformationDBAdapterInput_msg" element="db:GetHospitalInformationDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetHospitalInformationDBAdapterOutputCollection_msg">
        <wsdl:part name="GetHospitalInformationDBAdapterOutputCollection" element="db:GetHospitalInformationDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetHospitalInformationDBAdapter_ptt">
        <wsdl:operation name="GetHospitalInformationDBAdapter">
            <wsdl:input message="tns:GetHospitalInformationDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetHospitalInformationDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
