<?binding.jca GetMedicineInformationDBAdapter_db.jca?>
<wsdl:definitions name="GetMedicineInformationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetMedicineInformationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetMedicineInformationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter">
    <plt:partnerLinkType name="GetMedicineInformationDBAdapter_plt">
        <plt:role name="GetMedicineInformationDBAdapter_role">
            <plt:portType name="tns:GetMedicineInformationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter" schemaLocation="xsd/GetMedicineInformationDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:MedicamentosstockPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="MedicamentosstockCollection_msg">
        <wsdl:part name="MedicamentosstockCollection" element="top:MedicamentosstockCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetMedicineInformationDBAdapter_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:MedicamentosstockCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
