<wsdl:definitions
     name="PlaceOrderFileAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-BO/PlaceOrderFileAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-BO/PlaceOrderFileAdapter"
     xmlns:imp1="urn:oasis:names:specification:ubl:schema:xsd:Order-2"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="WriteFile_plt" >
    <plt:role name="WriteFile_role" >
      <plt:portType name="tns:WriteFile_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-BO/PlaceOrderFileAdapter"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="urn:oasis:names:specification:ubl:schema:xsd:Order-2" schemaLocation="xsd/UBL-Order-2.0.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="WriteFile_msg">
        <wsdl:part name="body" element="imp1:Order"/>
    </wsdl:message>
    <wsdl:portType name="WriteFile_ptt">
        <wsdl:operation name="WriteFile">
            <wsdl:input message="tns:WriteFile_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
