<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PlaceMedicineOrderBPELProcess"
     targetNamespace="http://xmlns.oracle.com/SeiLessons/HSN_BO/PlaceMedicineOrderBPELProcess"
     xmlns:ns2="urn:netdocs:schemas:document"
     xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_BO/PlaceMedicineOrderBPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="PlaceMedicineOrderBPELProcess">
        <plnk:role name="PlaceMedicineOrderBPELProcessProvider">
            <plnk:portType name="client:PlaceMedicineOrderBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"
                 schemaLocation="xsd/GetMedicineStockAndRequestedInformationDBAdapter.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:netdocs:schemas:document" schemaLocation="xsd/maindoc/ND-Invoice-1.0.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="PlaceMedicineOrderBPELProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="PlaceMedicineOrderBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:PlaceMedicineOrderBPELProcessRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
