<?binding.jca MedicineStockDBAdapter_db.jca?>
<wsdl:definitions name="MedicineStockDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-PopulateMedicineStock/MedicineStockDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-PopulateMedicineStock/MedicineStockDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockDBAdapter">
    <plt:partnerLinkType name="MedicineStockDBAdapter_plt">
        <plt:role name="MedicineStockDBAdapter_role">
            <plt:portType name="tns:MedicineStockDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockDBAdapter" schemaLocation="xsd/MedicineStockDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MedicamentosstockCollection_msg">
        <wsdl:part name="MedicamentosstockCollection" element="top:MedicamentosstockCollection"/>
    </wsdl:message>
    <wsdl:portType name="MedicineStockDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:MedicamentosstockCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
