<wsdl:definitions
     name="ReceiveMedicineStock"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-PopulateMedicineStock/ReceiveMedicineStock"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-PopulateMedicineStock/ReceiveMedicineStock"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://TargetNamespace.com/MedicinesStockPopulate"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="ReadFile_plt" >
    <plt:role name="ReadFile_role" >
      <plt:portType name="tns:ReadFile_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://TargetNamespace.com/MedicinesStockPopulate" schemaLocation="xsd/medicamentosValidos_1.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ReadFile_msg">
        <wsdl:part name="body" element="imp1:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="ReadFile_ptt">
        <wsdl:operation name="ReadFile">
            <wsdl:input message="tns:ReadFile_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
