<?binding.jca GetTriageInformationDBAdapter_db.jca?>
<wsdl:definitions name="GetTriageInformationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetTriageInformationDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageInformationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/GetTriageInformationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetTriageInformationDBAdapter_plt">
        <plt:role name="GetTriageInformationDBAdapter_role">
            <plt:portType name="tns:GetTriageInformationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetTriageInformationDBAdapter" schemaLocation="xsd/GetTriageInformationDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetTriageInformationDBAdapterInput_msg">
        <wsdl:part name="GetTriageInformationDBAdapterInput_msg" element="db:GetTriageInformationDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetTriageInformationDBAdapterOutputCollection_msg">
        <wsdl:part name="GetTriageInformationDBAdapterOutputCollection" element="db:GetTriageInformationDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetTriageInformationDBAdapter_ptt">
        <wsdl:operation name="GetTriageInformationDBAdapter">
            <wsdl:input message="tns:GetTriageInformationDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetTriageInformationDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
