<?binding.jca InsertMedicineInformationDBAdapter_db.jca?>
<wsdl:definitions name="InsertMedicineInformationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/InsertMedicineInformationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/InsertMedicineInformationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertMedicineInformationDBAdapter">
    <plt:partnerLinkType name="InsertMedicineInformationDBAdapter_plt">
        <plt:role name="InsertMedicineInformationDBAdapter_role">
            <plt:portType name="tns:InsertMedicineInformationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertMedicineInformationDBAdapter" schemaLocation="xsd/InsertMedicineInformationDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MedicinesinformationCollection_msg">
        <wsdl:part name="MedicinesinformationCollection" element="top:MedicinesinformationCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertMedicineInformationDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:MedicinesinformationCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
