<?binding.jca MedicineStockMedicineIDDBAdapter_db.jca?>
<wsdl:definitions name="MedicineStockMedicineIDDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/MedicineStockMedicineIDDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/MedicineStockMedicineIDDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockMedicineIDDBAdapter">
    <plt:partnerLinkType name="MedicineStockMedicineIDDBAdapter_plt">
        <plt:role name="MedicineStockMedicineIDDBAdapter_role">
            <plt:portType name="tns:MedicineStockMedicineIDDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MedicineStockMedicineIDDBAdapter" schemaLocation="xsd/MedicineStockMedicineIDDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MedicineStockMedicineIDDBAdapterSelect_inputParameters">
        <wsdl:part name="MedicineStockMedicineIDDBAdapterSelect_inputParameters" element="top:MedicineStockMedicineIDDBAdapterSelect_NOME_SUBSTANCIA_DOSEInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MedicamentosstockCollection_msg">
        <wsdl:part name="MedicamentosstockCollection" element="top:MedicamentosstockCollection"/>
    </wsdl:message>
    <wsdl:portType name="MedicineStockMedicineIDDBAdapter_ptt">
        <wsdl:operation name="MedicineStockMedicineIDDBAdapterSelect">
            <wsdl:input message="tns:MedicineStockMedicineIDDBAdapterSelect_inputParameters"/>
            <wsdl:output message="tns:MedicamentosstockCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
