<wsdl:definitions
     name="ReceivePatientReportFileAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-Project/ReceivePatientReportFileAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-Project/ReceivePatientReportFileAdapter"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://saude365.pt"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="ReadReport_plt" >
    <plt:role name="ReadReport_role" >
      <plt:portType name="tns:ReadReport_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://saude365.pt" schemaLocation="xsd/patient_report.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ReadReport_msg">
        <wsdl:part name="body" element="imp1:relatorio"/>
    </wsdl:message>
    <wsdl:portType name="ReadReport_ptt">
        <wsdl:operation name="ReadReport">
            <wsdl:input message="tns:ReadReport_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
