<?binding.jca ValidAddressFlagDBAdapter_db.jca?>
<wsdl:definitions name="ValidAddressFlagDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/ValidAddressFlagDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-Project/ValidAddressFlagDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ValidAddressFlagDBAdapter">
    <plt:partnerLinkType name="ValidAddressFlagDBAdapter_plt">
        <plt:role name="ValidAddressFlagDBAdapter_role">
            <plt:portType name="tns:ValidAddressFlagDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ValidAddressFlagDBAdapter" schemaLocation="xsd/ValidAddressFlagDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DoenteCollection_msg">
        <wsdl:part name="DoenteCollection" element="top:DoenteCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidAddressFlagDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:DoenteCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
