<?binding.jca GetSupplierInformationDBAdapter_db.jca?>
<wsdl:definitions name="GetSupplierInformationDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetSupplierInformationDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetSupplierInformationDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetSupplierInformationDBAdapter_plt">
        <plt:role name="GetSupplierInformationDBAdapter_role">
            <plt:portType name="tns:GetSupplierInformationDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter" schemaLocation="xsd/GetSupplierInformationDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetSupplierInformationDBAdapterInput_msg">
        <wsdl:part name="GetSupplierInformationDBAdapterInput_msg" element="db:GetSupplierInformationDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetSupplierInformationDBAdapterOutputCollection_msg">
        <wsdl:part name="GetSupplierInformationDBAdapterOutputCollection" element="db:GetSupplierInformationDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetSupplierInformationDBAdapter_ptt">
        <wsdl:operation name="GetSupplierInformationDBAdapter">
            <wsdl:input message="tns:GetSupplierInformationDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetSupplierInformationDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
