<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="JustInTimeStockBusinessRule_DecisionService_1"
     targetNamespace="http://xmlns.oracle.com/JustInTimeStockBusinessRule/JustInTimeStockBusinessRule_DecisionService_1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/JustInTimeStockBusinessRule/JustInTimeStockBusinessRule_DecisionService_1"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="JustInTimeStockBusinessRule.JustInTimeStockBusinessRule_DecisionService_1">
        <plnk:role name="IDecisionService">
            <plnk:portType name="tns:IDecisionService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/JustInTimeStockBusinessRule/JustInTimeStockBusinessRule_DecisionService_1"
         location="JustInTimeStockBusinessRule_DecisionService_1.wsdl"/>
</wsdl:definitions>
