<?binding.jca UpdateMedicinesStockDBAdapter_db.jca?>
<wsdl:definitions name="UpdateMedicinesStockDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/UpdateMedicinesStockDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/UpdateMedicinesStockDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateMedicinesStockDBAdapter">
    <plt:partnerLinkType name="UpdateMedicinesStockDBAdapter_plt">
        <plt:role name="UpdateMedicinesStockDBAdapter_role">
            <plt:portType name="tns:UpdateMedicinesStockDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateMedicinesStockDBAdapter" schemaLocation="xsd/UpdateMedicinesStockDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MedicamentosstockCollection_msg">
        <wsdl:part name="MedicamentosstockCollection" element="top:MedicamentosstockCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateMedicinesStockDBAdapter_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:MedicamentosstockCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
