<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../PlaceMedicineOrderBPELProcess.wsdl"/>
      <rootElement name="GetMedicineStockAndRequestedInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"/>
    </source>
    <source type="WSDL">
      <schema location="../GetSupplierInformationDBAdapter.wsdl"/>
      <rootElement name="GetSupplierInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter"/>
      <param name="getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection" />
    </source>
    <source type="WSDL">
      <schema location="../GetHospitalInformationDBAdapter.wsdl"/>
      <rootElement name="GetHospitalInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter"/>
      <param name="getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection" />
    </source>
    <source type="WSDL">
      <schema location="../GetMedicineInformationDBAdapter.wsdl"/>
      <rootElement name="MedicamentosstockCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"/>
      <param name="getMedicineInformationOutputVariable.MedicamentosstockCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PlaceOrderFileAdapter.wsdl"/>
      <rootElement name="Order" namespace="urn:oasis:names:specification:ubl:schema:xsd:Order-2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [MON MAY 06 17:30:11 PDT 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns7="urn:un:unece:uncefact:codelist:specification:66411:2001"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetSupplierInformationDBAdapter"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetHospitalInformationDBAdapter"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetSupplierInformationDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="urn:netdocs:schemas:message"
                xmlns:ns10="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns12="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
                xmlns:ns11="urn:un:unece:uncefact:codelist:specification:54217:2001"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-BO/PlaceOrderFileAdapter"
                xmlns:ns15="urn:un:unece:uncefact:codelist:specification:IANAMIMEMediaType:2003"
                xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetMedicineInformationDBAdapter"
                xmlns:ns8="urn:un:unece:uncefact:codelist:specification:5639:1988"
                xmlns:ns9="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetMedicineInformationDBAdapter"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns14="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:client="http://xmlns.oracle.com/SeiLessons/HSN_BO/PlaceMedicineOrderBPELProcess"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns2="urn:netdocs:schemas:document"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:imp1="urn:oasis:names:specification:ubl:schema:xsd:Order-2"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns13="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/GetHospitalInformationDBAdapter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns4 db ns0 plnk wsdl ns5 top client ns2 xsd ns1 ns3 ns7 ns10 ns12 ns11 ns6 ns15 ns8 ns9 ns14 jca imp1 ns13 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection"/>
  <xsl:param name="getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection"/>
  <xsl:param name="getMedicineInformationOutputVariable.MedicamentosstockCollection"/>
  <xsl:template match="/">
    <imp1:Order>
      <ns9:UBLVersionID>
        <xsl:value-of select="2.0"/>
      </ns9:UBLVersionID>
      <ns9:CustomizationID>
        <xsl:value-of select='"urn:oasis:names:specification:ubl:xpath:Order-2.0:sbs-1.0-draft"'/>
      </ns9:CustomizationID>
      <ns9:ProfileID>
        <xsl:value-of select='"bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-order-with-simple-response-draft"'/>
      </ns9:ProfileID>
      <ns9:ID>
        <xsl:value-of select="concat($getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:medicamentoid,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia,$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose,xp20:current-dateTime())"/>
      </ns9:ID>
      <ns9:SalesOrderID>
        <xsl:value-of select="oraext:generate-guid()"/>
      </ns9:SalesOrderID>
      <ns9:CopyIndicator>
        <xsl:value-of select='"false"'/>
      </ns9:CopyIndicator>
      <ns9:UUID>
        <xsl:value-of select="oraext:generate-guid()"/>
      </ns9:UUID>
      <ns9:IssueDate>
        <xsl:value-of select="xp20:current-date()"/>
      </ns9:IssueDate>
      <ns9:Note>
        <xsl:value-of select='"sample"'/>
      </ns9:Note>
      <ns12:BuyerCustomerParty>
        <ns9:CustomerAssignedAccountID>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns9:CustomerAssignedAccountID>
        <ns9:SupplierAssignedAccountID>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns9:SupplierAssignedAccountID>
        <ns12:Party>
          <ns12:PartyIdentification>
            <ns9:ID>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CUSTOMERACCOUNTID"/>
            </ns9:ID>
          </ns12:PartyIdentification>
          <ns12:PartyName>
            <ns9:Name>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:PARTYNAME"/>
            </ns9:Name>
          </ns12:PartyName>
          <ns12:PostalAddress>
            <ns9:StreetName>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:STREETNAME"/>
            </ns9:StreetName>
            <ns9:CityName>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CITYNAME"/>
            </ns9:CityName>
            <ns9:PostalZone>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:POSTALZONE"/>
            </ns9:PostalZone>
            <ns12:AddressLine>
              <ns9:Line>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:STREETNAME"/>
              </ns9:Line>
            </ns12:AddressLine>
            <ns12:Country>
              <ns9:IdentificationCode>
                <xsl:value-of select='"PT"'/>
              </ns9:IdentificationCode>
              <ns9:Name>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:COUNTRY"/>
              </ns9:Name>
            </ns12:Country>
          </ns12:PostalAddress>
          <ns12:PartyTaxScheme>
            <ns9:RegistrationName>
              <xsl:value-of select='"District Council"'/>
            </ns9:RegistrationName>
            <ns9:CompanyID>
              <xsl:value-of select="oraext:generate-guid()"/>
            </ns9:CompanyID>
            <ns9:ExemptionReason>
              <xsl:value-of select='"Local Authority"'/>
            </ns9:ExemptionReason>
            <ns12:TaxScheme>
              <ns9:ID>
                <xsl:value-of select='"PT VAT"'/>
              </ns9:ID>
              <ns9:TaxTypeCode>
                <xsl:value-of select='"VAT"'/>
              </ns9:TaxTypeCode>
            </ns12:TaxScheme>
          </ns12:PartyTaxScheme>
          <ns12:Contact>
            <ns9:Name>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CONTACTNAME"/>
            </ns9:Name>
            <ns9:Telephone>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CONTACTTELEPHONE"/>
            </ns9:Telephone>
            <ns9:ElectronicMail>
              <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CONTACTEMAIL"/>
            </ns9:ElectronicMail>
          </ns12:Contact>
        </ns12:Party>
      </ns12:BuyerCustomerParty>
      <ns12:SellerSupplierParty>
        <ns9:CustomerAssignedAccountID>
          <xsl:value-of select="oraext:generate-guid()"/>
        </ns9:CustomerAssignedAccountID>
        <ns12:Party>
          <ns12:PartyIdentification>
            <ns9:ID>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CUSTOMERACCOUNTID"/>
            </ns9:ID>
          </ns12:PartyIdentification>
          <ns12:PartyName>
            <ns9:Name>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PARTYNAME"/>
            </ns9:Name>
          </ns12:PartyName>
          <ns12:PostalAddress>
            <ns9:StreetName>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:STREETNAME"/>
            </ns9:StreetName>
            <ns9:CityName>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CITYNAME"/>
            </ns9:CityName>
            <ns9:PostalZone>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:POSTALZONE"/>
            </ns9:PostalZone>
            <ns12:AddressLine>
              <ns9:Line>
                <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:STREETNAME"/>
              </ns9:Line>
            </ns12:AddressLine>
            <ns12:Country>
              <ns9:Name>
                <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:COUNTRY"/>
              </ns9:Name>
            </ns12:Country>
          </ns12:PostalAddress>
          <ns12:Contact>
            <ns9:Name>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTNAME"/>
            </ns9:Name>
            <ns9:Telephone>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTTELEPHONE"/>
            </ns9:Telephone>
            <ns9:ElectronicMail>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CONTACTEMAIL"/>
            </ns9:ElectronicMail>
          </ns12:Contact>
        </ns12:Party>
      </ns12:SellerSupplierParty>
      <ns12:OrderLine>
        <ns12:LineItem>
          <ns9:ID>
            <xsl:value-of select="/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns1:MEDICAMENTOID"/>
          </ns9:ID>
          <ns9:Quantity>
            <xsl:attribute name="unitCode">
              <xsl:text disable-output-escaping="no">NU</xsl:text>
            </xsl:attribute>
            <xsl:value-of select="/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns1:QUANTIDADECRITICA + /ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns1:QUANTIDADEPEDIDA"/>
          </ns9:Quantity>
          <ns12:Price>
            <ns9:PriceAmount>
              <xsl:attribute name="currencyID">
                <xsl:text disable-output-escaping="no">EUR</xsl:text>
              </xsl:attribute>
              <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:PRICECHARGE"/>
            </ns9:PriceAmount>
            <ns9:BaseQuantity>
              <xsl:attribute name="unitCode">
                <xsl:text disable-output-escaping="no">NU</xsl:text>
              </xsl:attribute>
              <xsl:value-of select="/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns1:QUANTIDADEPEDIDA + /ns1:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/ns1:GetMedicineStockAndRequestedInformationDBAdapterOutput/ns1:QUANTIDADECRITICA"/>
            </ns9:BaseQuantity>
          </ns12:Price>
          <ns12:Item>
            <ns9:Description>
              <xsl:value-of select='concat(" Medicamento: ",$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome," Substancia Activa: ",$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:substancia," Dose: ",$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:dose)'/>
            </ns9:Description>
            <ns9:Name>
              <xsl:value-of select="$getMedicineInformationOutputVariable.MedicamentosstockCollection/top:MedicamentosstockCollection/top:Medicamentosstock/top:nome"/>
            </ns9:Name>
            <ns12:BuyersItemIdentification>
              <ns9:ID>
                <xsl:value-of select="$getHospitalInformationOutputVariable.GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutputCollection/ns3:GetHospitalInformationDBAdapterOutput/ns3:CUSTOMERACCOUNTID"/>
              </ns9:ID>
            </ns12:BuyersItemIdentification>
            <ns12:SellersItemIdentification>
              <ns9:ID>
                <xsl:value-of select="$getSupplierInformationOutputVariable.GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutputCollection/db:GetSupplierInformationDBAdapterOutput/db:CUSTOMERACCOUNTID"/>
              </ns9:ID>
            </ns12:SellersItemIdentification>
          </ns12:Item>
        </ns12:LineItem>
      </ns12:OrderLine>
    </imp1:Order>
  </xsl:template>
</xsl:stylesheet>
