<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../%20HSN-BO/GetMedicineStockAndRequestedInformationDBAdapter.wsdl"/>
      <rootElement name="GetMedicineStockAndRequestedInformationDBAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../%20HSN-BO/StockJustInTimeBPELProcess.wsdl"/>
      <rootElement name="process" namespace="http://xmlns.oracle.com/SeiLessons/HSN_BO/StockJustInTimeBPELProcess"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU APR 11 03:38:55 PDT 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns1="http://xmlns.oracle.com/SeiLessons/HSN_BO/StockJustInTimeBPELProcess"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeiLessons/HSN-BO/GetMedicineStockAndRequestedInformationDBAdapter"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetMedicineStockAndRequestedInformationDBAdapter"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt xsd wsdl tns db ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns1:process>
      <ns1:existenceQuantity>
        <xsl:value-of select="/db:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/db:GetMedicineStockAndRequestedInformationDBAdapterOutput/db:QUANTIDADEEXISTENTE"/>
      </ns1:existenceQuantity>
      <ns1:criticalQuantity>
        <xsl:value-of select="/db:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/db:GetMedicineStockAndRequestedInformationDBAdapterOutput/db:QUANTIDADECRITICA"/>
      </ns1:criticalQuantity>
      <ns1:requestedQuantity>
        <xsl:value-of select="/db:GetMedicineStockAndRequestedInformationDBAdapterOutputCollection/db:GetMedicineStockAndRequestedInformationDBAdapterOutput/db:QUANTIDADEPEDIDA"/>
      </ns1:requestedQuantity>
    </ns1:process>
  </xsl:template>
</xsl:stylesheet>
