<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../PlaceOrderFileAdapter.wsdl"/>
      <rootElement name="Order" namespace="urn:oasis:names:specification:ubl:schema:xsd:Order-2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PlaceOrderFileAdapter.wsdl"/>
      <rootElement name="Order" namespace="urn:oasis:names:specification:ubl:schema:xsd:Order-2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE MAY 07 12:58:21 PDT 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns0="urn:un:unece:uncefact:codelist:specification:66411:2001"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns3="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns5="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
                xmlns:ns4="urn:un:unece:uncefact:codelist:specification:54217:2001"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SeiLessons/HSN-BO/PlaceOrderFileAdapter"
                xmlns:ns8="urn:un:unece:uncefact:codelist:specification:IANAMIMEMediaType:2003"
                xmlns:ns1="urn:un:unece:uncefact:codelist:specification:5639:1988"
                xmlns:ns2="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns7="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:imp1="urn:oasis:names:specification:ubl:schema:xsd:Order-2"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns6="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 ns3 plt ns5 ns4 wsdl tns ns8 ns1 ns2 ns7 jca xsd imp1 ns6 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <xsl:copy-of select="/imp1:Order">
      <?oracle-xsl-mapper-position imp1:Order?>
    </xsl:copy-of>
  </xsl:template>
</xsl:stylesheet>
